export type GenericPageModals  =
| 'REMOVE_ORDER'
| 'EXPAND_IMAGE'
| 'ORDERS_FROM_PRODUCT'
;

export type UsersPageModals = GenericPageModals
| 'USER_INFOS'
| 'DEACTIVATE_USER'
| 'ACTIVATE_USER'
| 'USER_SUPPORT_MESSAGES'
| 'REPLY_MESSAGE'
| 'REPLY_MESSAGE_CONFIRM'
| 'SUPPORT_MESSAGE_TO_USER'
| 'SUPPORT_MESSAGE_TO_USER_CONFIRM'
;

export type UserDeactivatedMenuModals = 
| 'CONTACT_SUPPORT' 
| 'CONFIRM_SEND_MESSAGE' 
| 'LAST_SUPPORT_MESSAGES' 
| 'REPLY_SUPPORT_MESSAGE'
| 'SEND_REPLY_CONFIRM'

export type ProductPageModals = GenericPageModals 
| 'EDIT_JUSTIFY'
| 'CONFIRM_REMOVE_PRODUCT'
| 'REMOVE_PRODUCT_JUSTIFY'
| 'EDIT_PRODUCT_CONFIRM'
| 'PRODUCT_INFO'
| 'CONFIRM_ORDER'
| 'EDIT_PRODUCT'
| 'ORDER_PRODUCT_MENU'
| 'PRODUCT_REMOVE_JUSTIFY'
| 'MESSAGE_TO_SUPPORT'
| 'MESSAGE_TO_SUPPORT_CONFIRM'
| 'PRODUCT_MESSAGES_SUPPORT'
| 'ACTIVE_PRODUCT'
| 'ACTIVE_PRODUCT_CONFIRM'
| 'DELETE_PRODUCT_CONFIRM'
;

export type OrderPageModals = GenericPageModals
| 'ACCEPT_ORDER_CONFIRM'
| 'REJECT_ORDER_CONFIRM'
| 'ORDER_REJECTION_JUSTIFY'
| 'EDIT_ORDER_REJECTION_JUSTIFY'
| 'PRODUCT_OUTTA_STOCK_MESSAGE'
| 'NEW_ORDER_REJECTION_JUSTIFY_CONFIRM'
| 'RESET_PRODUCT_STOCK'
;

export type UserOrderPageModals = GenericPageModals
| 'PAY_ORDER_CONFIRM'
| 'PAY_ORDER'
| 'ORDER_REJECTION_JUSTIFY'
| 'CANCEL_ORDER'
;

export type UserProductPageModals = GenericPageModals
| 'COMMENT'
| 'USER_PRODUCT_INFO'
| 'REMOVE_PRODUCT_FROM_INVENTORY_CONFIRM'
| 'REMOVE_PRODUCT_FOR_SALE_CONFIRM'
| 'DELETE_PRODUCT_FOR_SALE_CONFIRM'
| 'PRODUCT_INFO'
| 'PRODUCT_INFO_IMAGE_EXPAND'
| 'EDIT_PRODUCT'
| 'EDIT_PRODUCT_CONFIRM'
| 'PRODUCT_REMOVE_JUSTIFY'
| 'PRODUCT_MESSAGES_SUPPORT'
| 'MESSAGE_TO_SUPPORT'
| 'MESSAGE_TO_SUPPORT_CONFIRM'
| 'REACTIVE_PRODUCT_CONFIRM'
;