import type { Metadata } from "next";
import { Geist, Geist_Mono, Nova_Square } from "next/font/google";
import "./globals.css";
import { ToastProvider } from "../contexts/ToastContext";
import { AuthInitializer } from "../components/auth/AuthInitializer";

const novaSquare = Nova_Square({
  variable: "--font-nova-square",
  weight: "400",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" >
      <body
        className={`${novaSquare.className} antialiased`}
        suppressHydrationWarning
      >
        <ToastProvider>
          <AuthInitializer>
            {children}
          </AuthInitializer>
        </ToastProvider>
      </body>
    </html>
  );
}
